-- create table users
-- (
--     id              varchar(25) auto_increment,
--     name            varchar(20) null,
--     script_access   varchar(20) null,
--     year       int         null,
--     constraint student_id
--         unique (student_id)
-- );
--
-- alter table users
--     add primary key (student_id);